#!/usr/bin/env bash

CONFIG_WORKERS="${CONFIG_WORKERS:-5}"
CONFIG_TIMEOUT="${CONFIG_TIMEOUT:-10}"

CONFIG_SUBFINDER_THREADS="${CONFIG_SUBFINDER_THREADS:-10}"
CONFIG_AMASS_TIMEOUT="${CONFIG_AMASS_TIMEOUT:-30m}"

CONFIG_DNSX_THREADS="${CONFIG_DNSX_THREADS:-100}"

CONFIG_HTTPX_THREADS="${CONFIG_HTTPX_THREADS:-50}"
CONFIG_HTTPX_TIMEOUT="${CONFIG_HTTPX_TIMEOUT:-10}"

CONFIG_KATANA_THREADS="${CONFIG_KATANA_THREADS:-10}"

CONFIG_NAABU_RATE="${CONFIG_NAABU_RATE:-1000}"

CONFIG_NUCLEI_RATE="${CONFIG_NUCLEI_RATE:-25}"
CONFIG_NUCLEI_THREADS="${CONFIG_NUCLEI_THREADS:-25}"

CONFIG_KEEP_CACHE="${CONFIG_KEEP_CACHE:-true}"
CONFIG_TIMESTAMP_OUTPUT="${CONFIG_TIMESTAMP_OUTPUT:-true}"

load_defaults() {
    export \
    CONFIG_WORKERS \
    CONFIG_TIMEOUT \
    CONFIG_SUBFINDER_THREADS \
    CONFIG_AMASS_TIMEOUT \
    CONFIG_DNSX_THREADS \
    CONFIG_HTTPX_THREADS \
    CONFIG_HTTPX_TIMEOUT \
    CONFIG_KATANA_THREADS \
    CONFIG_NAABU_RATE \
    CONFIG_NUCLEI_RATE \
    CONFIG_NUCLEI_THREADS \
    CONFIG_KEEP_CACHE \
    CONFIG_TIMESTAMP_OUTPUT
}